-- Generated by Oracle SQL Developer Data Modeler 4.1.5.907
--   at:        2018-01-06 13:08:58 CET
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c
-- AUTOR : MATEUSZ ZWEIGERT
  



DROP TABLE Adres CASCADE CONSTRAINTS ;

DROP TABLE Faktura_VAT CASCADE CONSTRAINTS ;

DROP TABLE Kategoria CASCADE CONSTRAINTS ;

DROP TABLE Klient CASCADE CONSTRAINTS ;

DROP TABLE Konto CASCADE CONSTRAINTS ;

DROP TABLE Magazyn CASCADE CONSTRAINTS ;

DROP TABLE Magazyn_has_Towar CASCADE CONSTRAINTS ;

DROP TABLE Osoba CASCADE CONSTRAINTS ;

DROP TABLE Osoba_has_Adres CASCADE CONSTRAINTS ;

DROP TABLE Pracownik CASCADE CONSTRAINTS ;

DROP TABLE Umowa CASCADE CONSTRAINTS ;

DROP TABLE Premia CASCADE CONSTRAINTS ;

DROP TABLE Producent CASCADE CONSTRAINTS ;

DROP TABLE Producent_has_Adres CASCADE CONSTRAINTS ;

DROP TABLE Rabat CASCADE CONSTRAINTS ;

DROP TABLE Telefon CASCADE CONSTRAINTS ;

DROP TABLE Towar CASCADE CONSTRAINTS ;

DROP TABLE Zamowienie CASCADE CONSTRAINTS ;

DROP TABLE Zamowienie_has_Towar CASCADE CONSTRAINTS ;

DROP TABLE Zdjecie CASCADE CONSTRAINTS ;

DROP SEQUENCE Adres_id_SEQ ;

DROP SEQUENCE Kategoria_id_SEQ ;

DROP SEQUENCE Konto_id_SEQ ;

DROP SEQUENCE Magazyn_id_SEQ ;

DROP SEQUENCE Osoba_id_SEQ ;

DROP SEQUENCE Umowa_id_SEQ ;

DROP SEQUENCE Premia_id_SEQ ;

DROP SEQUENCE Producent_id_SEQ ;

DROP SEQUENCE Rabat_id_SEQ ;

DROP SEQUENCE Telefon_id_SEQ ;

DROP SEQUENCE Towar_id_SEQ ;

DROP SEQUENCE Zamowienie_id_SEQ ;

DROP SEQUENCE Zdjecie_id_SEQ ;

CREATE SEQUENCE Adres_id_SEQ START WITH 1 NOCACHE ORDER ;

CREATE SEQUENCE Kategoria_id_SEQ START WITH 1 NOCACHE ORDER ;

CREATE SEQUENCE Konto_id_SEQ START WITH 1 NOCACHE ORDER ;

CREATE SEQUENCE Magazyn_id_SEQ START WITH 1 NOCACHE ORDER ;

CREATE SEQUENCE Osoba_id_SEQ START WITH 1 NOCACHE ORDER ;

CREATE SEQUENCE Umowa_id_SEQ START WITH 1 NOCACHE ORDER ;

CREATE SEQUENCE Premia_id_SEQ START WITH 1 NOCACHE ORDER ;

CREATE SEQUENCE Producent_id_SEQ START WITH 1 NOCACHE ORDER ;

CREATE SEQUENCE Rabat_id_SEQ START WITH 1 NOCACHE ORDER ;

CREATE SEQUENCE Telefon_id_SEQ START WITH 1 NOCACHE ORDER ;

CREATE SEQUENCE Towar_id_SEQ START WITH 1 NOCACHE ORDER ;

CREATE SEQUENCE Zamowienie_id_SEQ START WITH 1 NOCACHE ORDER ;

CREATE SEQUENCE Zdjecie_id_SEQ START WITH 1 NOCACHE ORDER ;

CREATE TABLE Adres
  (
    id     INTEGER NOT NULL ,
    ulica  VARCHAR2 (50 CHAR) NOT NULL ,
    miasto VARCHAR2 (50 CHAR) NOT NULL ,
    numer  VARCHAR2 (20 CHAR) ,
    kod    CHAR (10 CHAR) NOT NULL
  ) ;
ALTER TABLE Adres ADD CONSTRAINT Adres_PK PRIMARY KEY ( id ) ;


CREATE TABLE Faktura_VAT
  (
    Zamowienie_id    INTEGER NOT NULL ,
    nr               VARCHAR2 (30 CHAR) NOT NULL ,
    data_wystawienia DATE NOT NULL ,
    status           VARCHAR2 (20 CHAR) NOT NULL ,
    Pracownik_id     INTEGER NOT NULL
  ) ;
ALTER TABLE Faktura_VAT ADD CONSTRAINT Faktura_VAT_PK PRIMARY KEY ( Zamowienie_id ) ;


CREATE TABLE Kategoria
  (
    id   INTEGER NOT NULL ,
    opis VARCHAR2 (100) NOT NULL
  ) ;
ALTER TABLE Kategoria ADD CONSTRAINT Kategoria_PK PRIMARY KEY ( id ) ;


CREATE TABLE Klient
  (
    id        INTEGER NOT NULL ,
    data_dolaczenia DATE NOT NULL
  ) ;
ALTER TABLE Klient ADD CONSTRAINT Klient_PK PRIMARY KEY ( id ) ;


CREATE TABLE Konto
  (
    id             INTEGER NOT NULL ,
    login          VARCHAR2 (20 CHAR) NOT NULL ,
    haslo          VARCHAR2 (20 CHAR) NOT NULL ,
    salt           VARCHAR2 (50 CHAR) NOT NULL ,
    data_zalozenia DATE ,
    Klient_id      INTEGER NOT NULL
  ) ;
ALTER TABLE Konto ADD CONSTRAINT Konto_PK PRIMARY KEY ( id ) ;


CREATE TABLE Magazyn
  (
    id       INTEGER NOT NULL ,
    Adres_id INTEGER NOT NULL ,
    opis     VARCHAR2 (100 CHAR) NOT NULL
  ) ;
ALTER TABLE Magazyn ADD CONSTRAINT Magazyn_PK PRIMARY KEY ( id ) ;


CREATE TABLE Magazyn_has_Towar
  (
    Magazyn_id INTEGER NOT NULL ,
    Towar_id   INTEGER NOT NULL ,
    ilosc      INTEGER NOT NULL
  ) ;
ALTER TABLE Magazyn_has_Towar ADD CHECK ( ilosc >=0) ;
ALTER TABLE Magazyn_has_Towar ADD CONSTRAINT Magazyn_has_Towar_PK PRIMARY KEY ( Towar_id, Magazyn_id ) ;


CREATE TABLE Osoba
  (
    id       INTEGER NOT NULL ,
    imie     VARCHAR2 (30 CHAR) NOT NULL ,
    nazwisko VARCHAR2 (30 CHAR) NOT NULL ,
    pesel    CHAR (11 CHAR)
  ) ;
ALTER TABLE Osoba ADD CONSTRAINT Osoba_PK PRIMARY KEY ( id ) ;


CREATE TABLE Osoba_has_Adres
  (
    Osoba_id INTEGER NOT NULL ,
    Adres_id INTEGER NOT NULL
  ) ;
ALTER TABLE Osoba_has_Adres ADD CONSTRAINT Osoba_has_Adres_PK PRIMARY KEY ( Osoba_id, Adres_id ) ;


CREATE TABLE Pracownik
  (
    id         INTEGER NOT NULL ,
    pensja           NUMBER(10, 2) NOT NULL ,
    nr_ubezpieczenia CHAR (15 CHAR) ,
    NIP              CHAR (15 CHAR) NOT NULL
  ) ;
ALTER TABLE Pracownik ADD CHECK ( pensja>=1300) ;
ALTER TABLE Pracownik ADD CONSTRAINT Pracownik_PK PRIMARY KEY ( id ) ;

CREATE TABLE Umowa
  (
    id               INTEGER NOT NULL ,
    data_podpisania  DATE NOT NULL ,
    data_zakonczenia DATE,
    typ              VARCHAR2(20),
    aktualna         CHAR(1),
    Pracownik_Id INTEGER NOT NULL
  );
ALTER TABLE Umowa ADD CONSTRAINT Umowa_PK PRIMARY KEY ( id ) ;


CREATE TABLE Premia
  (
    id           INTEGER NOT NULL ,
    wartosc      NUMBER(10, 2) NOT NULL ,
    rok          CHAR (4 CHAR) NOT NULL ,
    miesiac      VARCHAR2 (15) NOT NULL ,
    Pracownik_Id INTEGER NOT NULL
  );
ALTER TABLE Premia ADD CONSTRAINT Premia_PK PRIMARY KEY ( id ) ;


CREATE TABLE Producent
  (
    id    INTEGER NOT NULL ,
    nazwa VARCHAR2 (20 CHAR) NOT NULL ,
    opis  VARCHAR2 (200 CHAR) NOT NULL
  ) ;
ALTER TABLE Producent ADD CONSTRAINT Producent_PK PRIMARY KEY ( id ) ;


CREATE TABLE Producent_has_Adres
  (
    Producent_id INTEGER NOT NULL ,
    Adres_id     INTEGER NOT NULL
  ) ;
ALTER TABLE Producent_has_Adres ADD CONSTRAINT Producent_id_Adres_id PRIMARY KEY ( Producent_id, Adres_id ) ;


CREATE TABLE Rabat
  (
    id              INTEGER NOT NULL ,
    termin_waznosci DATE NOT NULL ,
    procent         INTEGER NOT NULL ,
    wykorzystany    CHAR(1),
    Klient_id       INTEGER NOT NULL ,
    Towar_id        INTEGER NOT NULL
  ) ;
ALTER TABLE Rabat ADD CONSTRAINT Rabat_PK PRIMARY KEY ( id ) ;


CREATE TABLE Telefon
  (
    id              INTEGER NOT NULL ,
    nr_telefonu     VARCHAR2 (9 CHAR) NOT NULL ,
    data_pozyskania DATE ,
    Osoba_id        INTEGER NOT NULL
  ) ;
ALTER TABLE Telefon ADD CONSTRAINT Telefon_PK PRIMARY KEY ( id ) ;


CREATE TABLE Towar
  (
    id             INTEGER NOT NULL ,
    nazwa          VARCHAR2 (100 CHAR) NOT NULL ,
    data_produkcji DATE NOT NULL ,
    numer_seryjny  CHAR (15 CHAR) NOT NULL ,
    cena           NUMBER(10,2) NOT NULL ,
    Kategoria_Id   INTEGER NOT NULL ,
    Producent_Id   INTEGER NOT NULL
  ) ;
ALTER TABLE Towar ADD CHECK ( cena >= 1) ;
ALTER TABLE Towar ADD CONSTRAINT Towar_PK PRIMARY KEY ( id ) ;


CREATE TABLE Zamowienie
  (
    id              INTEGER NOT NULL ,
    data_zamowienia DATE NOT NULL ,
    zrealizowane    CHAR (1) NOT NULL ,
    oplacone        CHAR (1) NOT NULL ,
    Klient_Id       INTEGER NOT NULL
  ) ;
ALTER TABLE Zamowienie ADD CONSTRAINT Zamowienie_PK PRIMARY KEY ( id ) ;


CREATE TABLE Zamowienie_has_Towar
  (
    Zamowienie_id INTEGER NOT NULL ,
    Towar_id      INTEGER NOT NULL ,
    ilosc         INTEGER NOT NULL
  ) ;
ALTER TABLE Zamowienie_has_Towar ADD CONSTRAINT Zamowienie_has_Towar_PK PRIMARY KEY ( Zamowienie_id, Towar_id ) ;


CREATE TABLE Zdjecie
  (
    id              INTEGER NOT NULL ,
    nazwa           VARCHAR2 (30) NOT NULL ,
    rozszerzenie    CHAR(7),
    data_utworzenia DATE ,
    dane            VARCHAR2(1000),
    Towar_id        INTEGER NOT NULL
  ) ;
ALTER TABLE Zdjecie ADD CONSTRAINT Zdjecie_PK PRIMARY KEY ( id ) ;


ALTER TABLE Faktura_VAT ADD CONSTRAINT Faktura_VAT_Pracownik_FK FOREIGN KEY ( Pracownik_id ) REFERENCES Pracownik ( id ) NOT DEFERRABLE ;

ALTER TABLE Faktura_VAT ADD CONSTRAINT Faktura_VAT_Zamowienie_FK FOREIGN KEY ( Zamowienie_id ) REFERENCES Zamowienie ( id ) NOT DEFERRABLE ;

ALTER TABLE Klient ADD CONSTRAINT Klient_Osoba_FK FOREIGN KEY ( id ) REFERENCES Osoba ( id ) NOT DEFERRABLE ;

ALTER TABLE Konto ADD CONSTRAINT Konto_Klient_FK FOREIGN KEY ( Klient_id ) REFERENCES Klient ( id ) NOT DEFERRABLE ;

ALTER TABLE Magazyn ADD CONSTRAINT Magazyn_Adres_FK FOREIGN KEY ( Adres_id ) REFERENCES Adres ( id ) NOT DEFERRABLE ;

ALTER TABLE Magazyn_has_Towar ADD CONSTRAINT Magazyn_has_Towar_Magazyn_FK FOREIGN KEY ( Magazyn_id ) REFERENCES Magazyn ( id ) NOT DEFERRABLE ;

ALTER TABLE Magazyn_has_Towar ADD CONSTRAINT Magazyn_has_Towar_Towar_FK FOREIGN KEY ( Towar_id ) REFERENCES Towar ( id ) NOT DEFERRABLE ;

ALTER TABLE Osoba_has_Adres ADD CONSTRAINT Osoba_has_Adres_Adres_FK FOREIGN KEY ( Adres_id ) REFERENCES Adres ( id ) NOT DEFERRABLE ;

ALTER TABLE Osoba_has_Adres ADD CONSTRAINT Osoba_has_Adres_Osoba_FK FOREIGN KEY ( Osoba_id ) REFERENCES Osoba ( id ) NOT DEFERRABLE ;

ALTER TABLE Pracownik ADD CONSTRAINT Pracownik_Osoba_FK FOREIGN KEY ( id ) REFERENCES Osoba ( id ) NOT DEFERRABLE ;

ALTER TABLE Umowa ADD CONSTRAINT Umowa_Pracownik_FK FOREIGN KEY ( Pracownik_Id ) REFERENCES Pracownik ( id ) NOT DEFERRABLE ;

ALTER TABLE Premia ADD CONSTRAINT Premia_Pracownik_FK FOREIGN KEY ( Pracownik_Id ) REFERENCES Pracownik ( id ) NOT DEFERRABLE ;

ALTER TABLE Producent_has_Adres ADD CONSTRAINT Producent_has_Adres_Adres_FK FOREIGN KEY ( Adres_id ) REFERENCES Adres ( id ) NOT DEFERRABLE ;

ALTER TABLE Producent_has_Adres ADD CONSTRAINT Producent_has_Adres_Prod_FK FOREIGN KEY ( Producent_id ) REFERENCES Producent ( id ) NOT DEFERRABLE ;

ALTER TABLE Rabat ADD CONSTRAINT Rabat_Klient_FK FOREIGN KEY ( Klient_id ) REFERENCES Klient ( id ) NOT DEFERRABLE ;

ALTER TABLE Rabat ADD CONSTRAINT Rabat_Towar_FK FOREIGN KEY ( Towar_id ) REFERENCES Towar ( id ) NOT DEFERRABLE ;

ALTER TABLE Telefon ADD CONSTRAINT Telefon_Osoba_FK FOREIGN KEY ( Osoba_id ) REFERENCES Osoba ( id ) NOT DEFERRABLE ;

ALTER TABLE Towar ADD CONSTRAINT Towar_Kategoria_FK FOREIGN KEY ( Kategoria_Id ) REFERENCES Kategoria ( id ) NOT DEFERRABLE ;

ALTER TABLE Towar ADD CONSTRAINT Towar_Producent_FK FOREIGN KEY ( Producent_Id ) REFERENCES Producent ( id ) NOT DEFERRABLE ;

ALTER TABLE Zamowienie_has_Towar ADD CONSTRAINT Zamow_has_Towar_Zamow_FK FOREIGN KEY ( Zamowienie_id ) REFERENCES Zamowienie ( id ) NOT DEFERRABLE ;

ALTER TABLE Zamowienie ADD CONSTRAINT Zamowienie_Klient_FK FOREIGN KEY ( Klient_Id ) REFERENCES Klient ( id ) NOT DEFERRABLE ;

ALTER TABLE Zamowienie_has_Towar ADD CONSTRAINT Zamowienie_has_Towar_Towar_FK FOREIGN KEY ( Towar_id ) REFERENCES Towar ( id ) NOT DEFERRABLE ;

ALTER TABLE Zdjecie ADD CONSTRAINT Zdjecie_Towar_FK FOREIGN KEY ( Towar_id ) REFERENCES Towar ( id ) NOT DEFERRABLE ;

CREATE OR REPLACE TRIGGER Adres_id_TRG 
    BEFORE INSERT ON Adres 
    FOR EACH ROW 
BEGIN :NEW.id := Adres_id_SEQ.NEXTVAL;
END; 
/

CREATE OR REPLACE TRIGGER Kategoria_id_TRG 
    BEFORE INSERT ON Kategoria 
    FOR EACH ROW 
BEGIN :NEW.id := Kategoria_id_SEQ.NEXTVAL;
END; 
/


CREATE OR REPLACE TRIGGER Konto_id_TRG 
    BEFORE INSERT ON Konto 
    FOR EACH ROW 
BEGIN :NEW.id := Konto_id_SEQ.NEXTVAL;
END; 
/



CREATE OR REPLACE TRIGGER Magazyn_id_TRG 
    BEFORE INSERT ON Magazyn 
    FOR EACH ROW 
BEGIN :NEW.id := Magazyn_id_SEQ.NEXTVAL;
END; 
/



CREATE OR REPLACE TRIGGER Osoba_id_TRG 
    BEFORE INSERT ON Osoba 
    FOR EACH ROW 
BEGIN :NEW.id := Osoba_id_SEQ.NEXTVAL;
END; 
/

CREATE OR REPLACE TRIGGER Umowa_id_TRG 
    BEFORE INSERT ON Umowa 
    FOR EACH ROW 
BEGIN :NEW.id := Umowa_id_SEQ.NEXTVAL;
END; 
/

CREATE OR REPLACE TRIGGER Premia_id_TRG 
    BEFORE INSERT ON Premia 
    FOR EACH ROW 
BEGIN :NEW.id := Premia_id_SEQ.NEXTVAL;
END; 
/



CREATE OR REPLACE TRIGGER Producent_id_TRG 
    BEFORE INSERT ON Producent 
    FOR EACH ROW 
BEGIN :NEW.id := Producent_id_SEQ.NEXTVAL;
END; 
/



CREATE OR REPLACE TRIGGER Rabat_id_TRG 
    BEFORE INSERT ON Rabat 
    FOR EACH ROW 
BEGIN :NEW.id := Rabat_id_SEQ.NEXTVAL;
END; 
/



CREATE OR REPLACE TRIGGER Telefon_id_TRG 
    BEFORE INSERT ON Telefon 
    FOR EACH ROW 
BEGIN :NEW.id := Telefon_id_SEQ.NEXTVAL;
END; 
/



CREATE OR REPLACE TRIGGER Towar_id_TRG 
    BEFORE INSERT ON Towar 
    FOR EACH ROW 
BEGIN :NEW.id := Towar_id_SEQ.NEXTVAL;
END; 
/



CREATE OR REPLACE TRIGGER Zamowienie_id_TRG 
    BEFORE INSERT ON Zamowienie 
    FOR EACH ROW 
BEGIN :NEW.id := Zamowienie_id_SEQ.NEXTVAL;
END; 
/



CREATE OR REPLACE TRIGGER Zdjecie_id_TRG 
    BEFORE INSERT ON Zdjecie 
    FOR EACH ROW 
BEGIN :NEW.id := Zdjecie_id_SEQ.NEXTVAL;
END; 
/




-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            20
-- CREATE INDEX                             0
-- ALTER TABLE                             44
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                          15
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                         15
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
